version: '3.9'
services:
  palworld-dedicated-server:
    container_name: palworld-server
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    ports:
      - 8211:8211/udp
      - 25575:25575/udp
    environment:
      - TZ=Asia/Shanghai
      - ALWAYS_UPDATE_ON_START=true
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=false
      - BACKUP_ENABLED=true
      - BACKUP_CRON_EXPRESSION=0 * * * *
      - STEAMCMD_VALIDATE_FILES=true
      - SERVER_SETTINGS_MODE=auto # Change this to manual if you want to edit the config yourself
      - NETSERVERMAXTICKRATE=120
      - DIFFICULTY=None # 难度，None 或 Difficulty
      - DAYTIME_SPEEDRATE=1.000000 # 白天流逝速度倍率
      - NIGHTTIME_SPEEDRATE=1.000000 # 夜晚流逝速度倍率
      - EXP_RATE=1.000000 # 经验值倍率
      - PAL_CAPTURE_RATE=1.000000 # 捕捉概率倍率
      - PAL_SPAWN_NUM_RATE=1.000000 # 帕鲁出现数量倍率
      - PAL_DAMAGE_RATE_ATTACK=1.000000 # 帕鲁攻击伤害倍率
      - PAL_DAMAGE_RATE_DEFENSE=1.000000 # 帕鲁承受伤害倍率
      - PLAYER_DAMAGE_RATE_ATTACK=1.000000 # 玩家攻击伤害倍率
      - PLAYER_DAMAGE_RATE_DEFENSE=1.000000 # 玩家承受伤害倍率
      - PLAYER_STOMACH_DECREASE_RATE=1.000000 # 玩家饱食度降低倍率
      - PLAYER_STAMINA_DECREACE_RATE=1.000000 # 玩家耐力降低倍率
      - PLAYER_AUTO_HP_REGENE_RATE=1.000000 # 玩家生命值自然恢复倍率
      - PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP=1.000000 # 玩家睡眠时生命恢复倍率
      - PAL_STOMACH_DECREACE_RATE=1.000000 # 帕鲁饱食度降低倍率
      - PAL_STAMINA_DECREACE_RATE=1.000000 # 帕鲁耐力降低倍率
      - PAL_AUTO_HP_REGENE_RATE=1.000000 # 帕鲁生命值自然恢复倍率
      - PAL_AUTO_HP_REGENE_RATE_IN_SLEEP=1.000000 #帕鲁睡眠时生命恢复倍率
      - BUILD_OBJECT_DAMAGE_RATE=1.000000 # 对建筑物伤害倍率
      - BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=1.000000 # 建筑物劣化速度倍率
      - COLLECTION_DROP_RATE=1.000000 # 可采集物品掉落倍率
      - COLLECTION_OBJECT_HP_RATE=1.000000 # 可采集物品生命值倍率
      - COLLECTION_OBJECT_RESPAWN_SPEED_RATE=1.000000 # 可采集物品生成速率
      - ENEMY_DROP_ITEM_RATE=1.000000 # 敌方掉落物品倍率
      - DEATH_PENALTY=All # 死亡惩罚，None 不掉落，Item 只掉物品不掉装备，ItemAndEquipment 掉物品和装备，All 全都掉
      - ENABLE_PLAYER_TO_PLAYER_DAMAGE=false # 启用玩家对玩家伤害功能
      - ENABLE_FRIENDLY_FIRE=false # 启用友军伤害功能
      - ENABLE_INVADER_ENEMY=true # 启用袭击事件功能
      - ACTIVE_UNKO=false # 启用 UNKO 功能(大便功能)
      - ENABLE_AIM_ASSIST_PAD=true # 启用手柄瞄准辅助功能
      - ENABLE_AIM_ASSIST_KEYBOARD=false # 启用键盘瞄准辅助功能
      - DROP_ITEM_MAX_NUM=3000 # 掉落物品最大数量
      - DROP_ITEM_MAX_NUM_UNKO=100 # 掉落物品最大数量_UNKO
      - BASE_CAMP_MAX_NUM=128 # 大本营最大数量
      - BASE_CAMP_WORKER_MAXNUM=15 # 大本营工人最大数量
      - DROP_ITEM_ALIVE_MAX_HOURS=1.000000 # 掉落物品存在最大时长（小时） 
      - AUTO_RESET_GUILD_NO_ONLINE_PLAYERS=false # 自动重置没有在线玩家的公会
      - AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS=72.000000 # 无在线玩家时自动重置公会的时间（小时）
      - GUILD_PLAYER_MAX_NUM=20 # 公会玩家最大数量
      - PAL_EGG_DEFAULT_HATCHING_TIME=72.000000 # 帕鲁蛋默认孵化时间（小时）
      - WORK_SPEED_RATE=1.000000  # 工作速度倍率
      - IS_MULTIPLAY=false # 是否为多人游戏
      - IS_PVP=false # 是否为 PvP 游戏
      - CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP=false # 是否可以拾取其他公会的死亡掉落物
      - ENABLE_NON_LOGIN_PENALTY=true # 是否启用不登录惩罚
      - ENABLE_FAST_TRAVEL=true # 是否启用快速旅行
      - IS_START_LOCATION_SELECT_BY_MAP=true # 是否通过地图选择起始位置
      - EXIST_PLAYER_AFTER_LOGOUT=false # 是否在登出后保留玩家
      - ENABLE_DEFENSE_OTHER_GUILD_PLAYER=false # 是否启用对其他公会玩家的防御
      - COOP_PLAYER_MAX_NUM=4 # 合作玩家最大数量
      - MAX_PLAYERS=32 # 服务器玩家最大数量
      - SERVER_NAME="Aether's Server" # 服务器名称
      - SERVER_DESCRIPTION="" # 服务器描述
      - ADMIN_PASSWORD=adminPasswordHere # 管理员密码
      - SERVER_PASSWORD=serverPasswordHere # 服务器密码
      - PUBLIC_PORT=8211 # 公共端口
      - PUBLIC_IP=
      - RCON_ENABLED=false
      - RCON_PORT=25575
      - REGION=
      - USEAUTH=true
      - BAN_LIST_URL=https://api.palworldgame.com/api/banlist.txt
    volumes:
      - /home/aether/.palworld:/palworld
