---
version: '3.3'
services:
  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - /home/aether/.komga:/config
      - /media/data0/:/data
    ports:
      - 25600:25600
    # remove the whole environment section if you don't need it
    environment:
      - TZ=Asia/Shanghai
      - JAVA_TOOL_OPTIONS=-Xmx4g 
    restart: unless-stopped
