version: "3"

networks:
  qbittorrent:
    enable_ipv6: true
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: "192.168.8.0/24"
          gateway: "192.168.8.1"
        - subnet: "fdb8:f550:de95::/64"
          gateway: "fdb8:f550:de95::1"

services:
  jellyfin:
    image: nyanmisaka/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    privileged: true
    volumes:
      - /home/aether/.media_streaming_stack/jellyfin_config:/config
      - /media/data0/:/data/
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/aether/.media_streaming_stack/sonarr_config:/config
      - /media/data0/:/data/
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/aether/.media_streaming_stack/radarr_config:/config
      - /media/data0/:/data/
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /home/aether/.media_streaming_stack/bazarr_config:/config
      - /media/data0/:/data/
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
      - TZ=Asia/Shanghai
    ports:
      - 5055:5055
    volumes:
      - /home/aether/.media_streaming_stack/jellyseerr_config:/app/config
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
    volumes:
      - /home/aether/.media_streaming_stack/jackett:/config
      - /media/data0/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jproxy:
    image: luckypuppy514/jproxy:latest
    container_name: jproxy
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 8117:8117
    volumes:
      - /home/aether/.media_streaming_stack/jproxy:/app/database

  qbittorrent:
    image: linuxserver/qbittorrent:4.6.2
    container_name: qbittorrent
    networks:
      qbittorrent:
        ipv4_address: 192.168.8.137
        ipv6_address: fdb8:f550:de95::137
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8923
    volumes:
      - /home/aether/.media_streaming_stack/qbittorrent:/config
      - /media/data0/download:/downloads
    restart: unless-stopped

