---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- logo:
    icon: homepage.png

- search:
    provider: google
    focus: true
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: long

